name: "Run Tests"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: "Test (node 16)"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3

      # Test pattern-matching engine
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: "Run Engine Tests"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path src/engine/Cargo.toml

      # Test transformation library
      - name: "Use Node.js 16"
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: "Start MongoDB"
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "5.0"

      - name: "Install Dependencies"
        run: npm install -g npm && npm install && npm run build

      - name: "Run Tests (JS)"
        run: npm test

