name: "Tests"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  engine:
    name: "Engine"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3

      # Test pattern-matching engine
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: "Run Tests"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path src/engine/Cargo.toml

      - name: Run benchmark
        run: cd src/engine/crates/engine && cargo bench -- --output-format bencher | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: src/engine/crates/engine/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true

  js:
    name: "Transformation"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3

      - name: "Use Node.js 16"
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: "Start MongoDB"
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "5.0"

      - name: "Install Dependencies"
        run: npm install -g npm && npm install && npm run build

      - name: "Run Tests"
        run: npm test

